version: '3'
services:
  api-loto-frontend:
    image: edinilsonsilva/loto-frontend:latest
    container_name: api-loto-frontend
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_URL_API_V1=${NEXT_PUBLIC_URL_API_V1}
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge