spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${SPRING_APPLICATION_NAME:loto}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate.dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    open-in-view: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Loto}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:@nestec123@}
  flyway:
    enabled: ${SPRING_DATASOURCE_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    placeholder-replacement: true
    schemas:
      - public
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
  servlet:
    multipart:
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:200MB}
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:200MB}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:bateraed@gmail.com}
    #password: '@loto123@'
    password: ${SPRING_MAIL_PASSWORD:npgc rdeh gjst prwl}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            required: true
            enable: ${SPRING_MAIL_SMTP_AUTH_STARTTLS_ENABLE:true}
          ssl:
            enable: ${SPRING_MAIL_SMTP_AUTH_SSL_ENABLE:false}

server:
  error:
    include-stacktrace: never
    include-message: always
  port: ${SERVER_PORT:8080}

loto:
  caixa:
    api-path: ${LOTO_CAIXA_API_PATH:https://servicebus2.caixa.gov.br/portaldeloterias/api}
  auth:
    expiration-in-minutes: ${LOTO_AUTH_EXPIRATION_IN_MINUTES:60}
    secret-key: ${LOTO_AUTH_SECRET_KEY:4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P}
    issuer: ${LOTO_AUTH_ISSUER:loto-api}
  efiCredential:
    clientId: ${LOTO_EFI_CREDENTIAL_CLIENT_ID:Client_Id_13f6bd7d7006a2f03621414db9e40899b9dd0796}
    clientSecret: ${LOTO_EFI_CREDENTIAL_CLIENT_SECRET:Client_Secret_a9a073331319289acc02c4969ddceed49911b003}
    certificate: ${LOTO_EFI_CREDENTIAL_CERTIFICATE:certificate}
    sandbox: ${LOTO_EFI_CREDENTIAL_SENDBOX:true}
    debug: ${LOTO_EFI_CREDENTIAL_DEBUG:true}

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:basic}