spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: loto
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/Loto}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:@nestec123@}
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
server:
  error:
    include-stacktrace: never
  port: 8080